INSERT INTO public.countries (id, title) VALUES (1, 'Россия');
INSERT INTO public.countries (id, title) VALUES (19, 'Австралия');
INSERT INTO public.countries (id, title) VALUES (20, 'Австрия');
INSERT INTO public.countries (id, title) VALUES (5, 'Азербайджан');
INSERT INTO public.countries (id, title) VALUES (21, 'Албания');
INSERT INTO public.countries (id, title) VALUES (22, 'Алжир');
INSERT INTO public.countries (id, title) VALUES (53, 'Виргинские острова, США');
INSERT INTO public.countries (id, title) VALUES (23, 'Американское Самоа');
INSERT INTO public.countries (id, title) VALUES (24, 'Ангилья');
INSERT INTO public.countries (id, title) VALUES (25, 'Ангола');
INSERT INTO public.countries (id, title) VALUES (26, 'Андорра');
INSERT INTO public.countries (id, title) VALUES (27, 'Антигуа и Барбуда');
INSERT INTO public.countries (id, title) VALUES (28, 'Аргентина');
INSERT INTO public.countries (id, title) VALUES (6, 'Армения');
INSERT INTO public.countries (id, title) VALUES (29, 'Аруба');
INSERT INTO public.countries (id, title) VALUES (30, 'Афганистан');
INSERT INTO public.countries (id, title) VALUES (31, 'Багамы');
INSERT INTO public.countries (id, title) VALUES (32, 'Бангладеш');
INSERT INTO public.countries (id, title) VALUES (33, 'Барбадос');
INSERT INTO public.countries (id, title) VALUES (34, 'Бахрейн');
INSERT INTO public.countries (id, title) VALUES (35, 'Белиз');
INSERT INTO public.countries (id, title) VALUES (3, 'Беларусь');
INSERT INTO public.countries (id, title) VALUES (36, 'Бельгия');
INSERT INTO public.countries (id, title) VALUES (37, 'Бенин');
INSERT INTO public.countries (id, title) VALUES (38, 'Бермуды');
INSERT INTO public.countries (id, title) VALUES (39, 'Болгария');
INSERT INTO public.countries (id, title) VALUES (40, 'Боливия');
INSERT INTO public.countries (id, title) VALUES (41, 'Босния и Герцеговина');
INSERT INTO public.countries (id, title) VALUES (42, 'Ботсвана');
INSERT INTO public.countries (id, title) VALUES (43, 'Бразилия');
INSERT INTO public.countries (id, title) VALUES (49, 'Великобритания');
INSERT INTO public.countries (id, title) VALUES (52, 'Виргинские острова, Великобритания');
INSERT INTO public.countries (id, title) VALUES (44, 'Бруней');
INSERT INTO public.countries (id, title) VALUES (45, 'Буркина-Фасо');
INSERT INTO public.countries (id, title) VALUES (46, 'Бурунди');
INSERT INTO public.countries (id, title) VALUES (48, 'Вануату');
INSERT INTO public.countries (id, title) VALUES (50, 'Венгрия');
INSERT INTO public.countries (id, title) VALUES (51, 'Венесуэла');
INSERT INTO public.countries (id, title) VALUES (54, 'Восточный Тимор');
INSERT INTO public.countries (id, title) VALUES (55, 'Вьетнам');
INSERT INTO public.countries (id, title) VALUES (56, 'Габон');
INSERT INTO public.countries (id, title) VALUES (57, 'Гаити');
INSERT INTO public.countries (id, title) VALUES (58, 'Гайана');
INSERT INTO public.countries (id, title) VALUES (61, 'Гваделупа');
INSERT INTO public.countries (id, title) VALUES (62, 'Гватемала');
INSERT INTO public.countries (id, title) VALUES (63, 'Гвинея');
INSERT INTO public.countries (id, title) VALUES (64, 'Гвинея-Бисау');
INSERT INTO public.countries (id, title) VALUES (65, 'Германия');
INSERT INTO public.countries (id, title) VALUES (66, 'Гибралтар');
INSERT INTO public.countries (id, title) VALUES (67, 'Гондурас');
INSERT INTO public.countries (id, title) VALUES (68, '');
INSERT INTO public.countries (id, title) VALUES (69, 'Гренада');
INSERT INTO public.countries (id, title) VALUES (70, 'Гренландия');
INSERT INTO public.countries (id, title) VALUES (71, 'Греция');
INSERT INTO public.countries (id, title) VALUES (7, 'Грузия');
INSERT INTO public.countries (id, title) VALUES (72, 'Гуам');
INSERT INTO public.countries (id, title) VALUES (73, 'Дания');
INSERT INTO public.countries (id, title) VALUES (101, 'Конго, демократическая республика');
INSERT INTO public.countries (id, title) VALUES (231, 'Джибути');
INSERT INTO public.countries (id, title) VALUES (74, 'Доминика');
INSERT INTO public.countries (id, title) VALUES (75, 'Доминиканская Республика');
INSERT INTO public.countries (id, title) VALUES (76, 'Египет');
INSERT INTO public.countries (id, title) VALUES (77, 'Замбия');
INSERT INTO public.countries (id, title) VALUES (79, 'Зимбабве');
INSERT INTO public.countries (id, title) VALUES (8, 'Израиль');
INSERT INTO public.countries (id, title) VALUES (80, 'Индия');
INSERT INTO public.countries (id, title) VALUES (81, 'Индонезия');
INSERT INTO public.countries (id, title) VALUES (82, 'Иордания');
INSERT INTO public.countries (id, title) VALUES (83, 'Ирак');
INSERT INTO public.countries (id, title) VALUES (84, 'Иран');
INSERT INTO public.countries (id, title) VALUES (85, 'Ирландия');
INSERT INTO public.countries (id, title) VALUES (86, 'Исландия');
INSERT INTO public.countries (id, title) VALUES (87, 'Испания');
INSERT INTO public.countries (id, title) VALUES (88, 'Италия');
INSERT INTO public.countries (id, title) VALUES (89, 'Йемен');
INSERT INTO public.countries (id, title) VALUES (173, 'Северная Корея');
INSERT INTO public.countries (id, title) VALUES (90, 'Кабо-Верде');
INSERT INTO public.countries (id, title) VALUES (4, 'Казахстан');
INSERT INTO public.countries (id, title) VALUES (149, 'Острова Кайман');
INSERT INTO public.countries (id, title) VALUES (91, 'Камбоджа');
INSERT INTO public.countries (id, title) VALUES (92, 'Камерун');
INSERT INTO public.countries (id, title) VALUES (10, 'Канада');
INSERT INTO public.countries (id, title) VALUES (93, 'Катар');
INSERT INTO public.countries (id, title) VALUES (94, 'Кения');
INSERT INTO public.countries (id, title) VALUES (95, 'Кипр');
INSERT INTO public.countries (id, title) VALUES (11, 'Кыргызстан');
INSERT INTO public.countries (id, title) VALUES (96, 'Кирибати');
INSERT INTO public.countries (id, title) VALUES (97, 'Китай');
INSERT INTO public.countries (id, title) VALUES (98, 'Колумбия');
INSERT INTO public.countries (id, title) VALUES (99, 'Коморы');
INSERT INTO public.countries (id, title) VALUES (102, 'Коста-Рика');
INSERT INTO public.countries (id, title) VALUES (103, 'Кот-д''Ивуар');
INSERT INTO public.countries (id, title) VALUES (104, 'Куба');
INSERT INTO public.countries (id, title) VALUES (105, 'Кувейт');
INSERT INTO public.countries (id, title) VALUES (106, 'Лаос');
INSERT INTO public.countries (id, title) VALUES (12, 'Латвия');
INSERT INTO public.countries (id, title) VALUES (107, 'Лесото');
INSERT INTO public.countries (id, title) VALUES (108, 'Либерия');
INSERT INTO public.countries (id, title) VALUES (109, 'Ливан');
INSERT INTO public.countries (id, title) VALUES (110, 'Ливия');
INSERT INTO public.countries (id, title) VALUES (13, 'Литва');
INSERT INTO public.countries (id, title) VALUES (111, 'Лихтенштейн');
INSERT INTO public.countries (id, title) VALUES (112, 'Люксембург');
INSERT INTO public.countries (id, title) VALUES (113, 'Маврикий');
INSERT INTO public.countries (id, title) VALUES (114, 'Мавритания');
INSERT INTO public.countries (id, title) VALUES (115, 'Мадагаскар');
INSERT INTO public.countries (id, title) VALUES (116, '');
INSERT INTO public.countries (id, title) VALUES (117, 'Северная Македония');
INSERT INTO public.countries (id, title) VALUES (118, 'Малави');
INSERT INTO public.countries (id, title) VALUES (119, 'Малайзия');
INSERT INTO public.countries (id, title) VALUES (120, 'Мали');
INSERT INTO public.countries (id, title) VALUES (121, 'Мальдивы');
INSERT INTO public.countries (id, title) VALUES (122, 'Мальта');
INSERT INTO public.countries (id, title) VALUES (123, 'Марокко');
INSERT INTO public.countries (id, title) VALUES (124, 'Мартиника');
INSERT INTO public.countries (id, title) VALUES (125, 'Маршалловы Острова');
INSERT INTO public.countries (id, title) VALUES (126, 'Мексика');
INSERT INTO public.countries (id, title) VALUES (128, 'Мозамбик');
INSERT INTO public.countries (id, title) VALUES (15, 'Молдова');
INSERT INTO public.countries (id, title) VALUES (129, 'Монако');
INSERT INTO public.countries (id, title) VALUES (130, 'Монголия');
INSERT INTO public.countries (id, title) VALUES (131, 'Монтсеррат');
INSERT INTO public.countries (id, title) VALUES (132, 'Мьянма');
INSERT INTO public.countries (id, title) VALUES (133, 'Намибия');
INSERT INTO public.countries (id, title) VALUES (134, 'Науру');
INSERT INTO public.countries (id, title) VALUES (135, 'Непал');
INSERT INTO public.countries (id, title) VALUES (136, 'Нигер');
INSERT INTO public.countries (id, title) VALUES (137, 'Нигерия');
INSERT INTO public.countries (id, title) VALUES (139, 'Нидерланды');
INSERT INTO public.countries (id, title) VALUES (140, 'Никарагуа');
INSERT INTO public.countries (id, title) VALUES (141, 'Ниуэ');
INSERT INTO public.countries (id, title) VALUES (143, 'Новая Каледония');
INSERT INTO public.countries (id, title) VALUES (142, 'Новая Зеландия');
INSERT INTO public.countries (id, title) VALUES (144, 'Норвегия');
INSERT INTO public.countries (id, title) VALUES (145, 'Объединенные Арабские Эмираты');
INSERT INTO public.countries (id, title) VALUES (146, 'Оман');
INSERT INTO public.countries (id, title) VALUES (150, 'Острова Кука');
INSERT INTO public.countries (id, title) VALUES (152, 'Пакистан');
INSERT INTO public.countries (id, title) VALUES (153, 'Палау');
INSERT INTO public.countries (id, title) VALUES (154, 'Палестинская автономия');
INSERT INTO public.countries (id, title) VALUES (155, 'Панама');
INSERT INTO public.countries (id, title) VALUES (156, 'Папуа — Новая Гвинея');
INSERT INTO public.countries (id, title) VALUES (157, 'Парагвай');
INSERT INTO public.countries (id, title) VALUES (158, 'Перу');
INSERT INTO public.countries (id, title) VALUES (160, 'Польша');
INSERT INTO public.countries (id, title) VALUES (161, 'Португалия');
INSERT INTO public.countries (id, title) VALUES (162, 'Пуэрто-Рико');
INSERT INTO public.countries (id, title) VALUES (100, 'Конго');
INSERT INTO public.countries (id, title) VALUES (163, 'Реюньон');
INSERT INTO public.countries (id, title) VALUES (164, 'Руанда');
INSERT INTO public.countries (id, title) VALUES (165, 'Румыния');
INSERT INTO public.countries (id, title) VALUES (9, 'США');
INSERT INTO public.countries (id, title) VALUES (166, 'Сальвадор');
INSERT INTO public.countries (id, title) VALUES (167, 'Самоа');
INSERT INTO public.countries (id, title) VALUES (168, 'Сан-Марино');
INSERT INTO public.countries (id, title) VALUES (169, 'Сан-Томе и Принсипи');
INSERT INTO public.countries (id, title) VALUES (170, 'Саудовская Аравия');
INSERT INTO public.countries (id, title) VALUES (171, 'Эсватини');
INSERT INTO public.countries (id, title) VALUES (174, 'Северные Марианские острова');
INSERT INTO public.countries (id, title) VALUES (175, 'Сейшелы');
INSERT INTO public.countries (id, title) VALUES (176, 'Сенегал');
INSERT INTO public.countries (id, title) VALUES (177, 'Сент-Винсент и Гренадины');
INSERT INTO public.countries (id, title) VALUES (178, 'Сент-Китс и Невис');
INSERT INTO public.countries (id, title) VALUES (179, 'Сент-Люсия');
INSERT INTO public.countries (id, title) VALUES (180, 'Сент-Пьер и Микелон');
INSERT INTO public.countries (id, title) VALUES (181, 'Сербия');
INSERT INTO public.countries (id, title) VALUES (182, 'Сингапур');
INSERT INTO public.countries (id, title) VALUES (183, 'Сирия');
INSERT INTO public.countries (id, title) VALUES (184, 'Словакия');
INSERT INTO public.countries (id, title) VALUES (185, 'Словения');
INSERT INTO public.countries (id, title) VALUES (186, 'Соломоновы Острова');
INSERT INTO public.countries (id, title) VALUES (187, 'Сомали');
INSERT INTO public.countries (id, title) VALUES (188, 'Судан');
INSERT INTO public.countries (id, title) VALUES (189, 'Суринам');
INSERT INTO public.countries (id, title) VALUES (190, 'Сьерра-Леоне');
INSERT INTO public.countries (id, title) VALUES (16, 'Таджикистан');
INSERT INTO public.countries (id, title) VALUES (191, 'Таиланд');
INSERT INTO public.countries (id, title) VALUES (192, 'Тайвань');
INSERT INTO public.countries (id, title) VALUES (193, 'Танзания');
INSERT INTO public.countries (id, title) VALUES (194, 'Того');
INSERT INTO public.countries (id, title) VALUES (195, 'Токелау');
INSERT INTO public.countries (id, title) VALUES (196, 'Тонга');
INSERT INTO public.countries (id, title) VALUES (197, 'Тринидад и Тобаго');
INSERT INTO public.countries (id, title) VALUES (198, 'Тувалу');
INSERT INTO public.countries (id, title) VALUES (199, 'Тунис');
INSERT INTO public.countries (id, title) VALUES (17, 'Туркменистан');
INSERT INTO public.countries (id, title) VALUES (200, 'Турция');
INSERT INTO public.countries (id, title) VALUES (201, 'Уганда');
INSERT INTO public.countries (id, title) VALUES (18, 'Узбекистан');
INSERT INTO public.countries (id, title) VALUES (2, 'Украина');
INSERT INTO public.countries (id, title) VALUES (203, 'Уругвай');
INSERT INTO public.countries (id, title) VALUES (204, 'Фарерские острова');
INSERT INTO public.countries (id, title) VALUES (127, 'Микронезия, федеративные штаты');
INSERT INTO public.countries (id, title) VALUES (205, 'Фиджи');
INSERT INTO public.countries (id, title) VALUES (206, 'Филиппины');
INSERT INTO public.countries (id, title) VALUES (207, 'Финляндия');
INSERT INTO public.countries (id, title) VALUES (208, 'Фолклендские острова');
INSERT INTO public.countries (id, title) VALUES (209, 'Франция');
INSERT INTO public.countries (id, title) VALUES (210, 'Французская Гвиана');
INSERT INTO public.countries (id, title) VALUES (211, 'Французская Полинезия');
INSERT INTO public.countries (id, title) VALUES (212, 'Хорватия');
INSERT INTO public.countries (id, title) VALUES (213, 'Центральноафриканская Республика');
INSERT INTO public.countries (id, title) VALUES (214, 'Чад');
INSERT INTO public.countries (id, title) VALUES (230, 'Черногория');
INSERT INTO public.countries (id, title) VALUES (215, 'Чехия');
INSERT INTO public.countries (id, title) VALUES (216, 'Чили');
INSERT INTO public.countries (id, title) VALUES (217, 'Швейцария');
INSERT INTO public.countries (id, title) VALUES (218, 'Швеция');
INSERT INTO public.countries (id, title) VALUES (220, 'Шри-Ланка');
INSERT INTO public.countries (id, title) VALUES (221, 'Эквадор');
INSERT INTO public.countries (id, title) VALUES (222, 'Экваториальная Гвинея');
INSERT INTO public.countries (id, title) VALUES (223, 'Эритрея');
INSERT INTO public.countries (id, title) VALUES (14, 'Эстония');
INSERT INTO public.countries (id, title) VALUES (224, 'Эфиопия');
INSERT INTO public.countries (id, title) VALUES (227, 'Южно-Африканская Республика');
INSERT INTO public.countries (id, title) VALUES (226, 'Южная Корея');
INSERT INTO public.countries (id, title) VALUES (228, 'Ямайка');
INSERT INTO public.countries (id, title) VALUES (229, 'Япония');
INSERT INTO public.countries (id, title) VALUES (148, 'Остров Норфолк');
INSERT INTO public.countries (id, title) VALUES (172, 'Святая Елена');
INSERT INTO public.countries (id, title) VALUES (151, 'Острова Теркс и Кайкос');
INSERT INTO public.countries (id, title) VALUES (202, 'Уоллис и Футуна');
