CREATE TABLE if NOT EXISTS PUBLIC.cities
(
    id     INTEGER NOT NULL PRIMARY KEY,
    area   VARCHAR(128),
    region VARCHAR(128),
    title  VARCHAR(128)
    );

CREATE TABLE if NOT EXISTS PUBLIC.countries
(
    id    INTEGER NOT NULL PRIMARY KEY,
    title VARCHAR(128)
    );


CREATE TABLE if NOT EXISTS PUBLIC.region
(
    id    INTEGER NOT NULL PRIMARY KEY,
    title VARCHAR(128)
    );
